### PR TITLE
Redirect v1alpha1 to v1beta1

### PR DESCRIPTION
**Pull request by fao89**
Temporarily redirect v1alpha1 to v1beta1
Once we bump AEE on [openstack-operator](https://github.com/openstack-k8s-operators/openstack-operator/blob/main/main.go#L51) and [dataplane-operator](https://github.com/openstack-k8s-operators/dataplane-operator/blob/main/main.go#L40) we can remove this
ref: https://github.com/openstack-k8s-operators/dataplane-operator/pull/478

### CODE REVIEW

**Review by rebtoor — COMMENTED** [review]
Excellent work @fao89 !

+2 for me

**Review by slagle — APPROVED** [review]

**Comment by rabi** [comment]
Does not look like this helped. Prow jobs are broken in dataplane-operator. I tried to bump ansiblee there[1] and that did not help either  https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_dataplane-operator/571/pull-ci-openstack-k8s-operators-dataplane-operator-main-dataplane-operator-build-deploy-kuttl/1734459433381007360. 

[1] https://github.com/openstack-k8s-operators/dataplane-operator/pull/571

**Pull request merged**
