### PR TITLE
Use play vs playbook terminology correctly

### PR DESCRIPTION
**Pull request by bshephar**
An Ansible Play is not the same as an Ansible Playbook. This change corrects some of the terminology and makes openstack-ansibleee-operator consistent with the dataplane-operator

### CODE REVIEW

**Review by slagle — COMMENTED** [review]
this LGTM. as mentioned on the other review, we should probably change the name of the field as well to not be "play"

**Comment by jpodivin** [comment]
Can we move this to a review proper now, or is there some more work left to do?

**Review by jpodivin — APPROVED** [review]

**Comment by rebtoor** [comment]
/hold

we should wait for openstack-operator bump as stated by @rabi [here](https://github.com/openstack-k8s-operators/install_yamls/pull/847#issuecomment-2162042593)

**Comment by rebtoor** [comment]
recheck

Added Depends-On

**Comment by bshephar** [comment]
> /hold
> 
> we should wait for openstack-operator bump as stated by @rabi [here](https://github.com/openstack-k8s-operators/install_yamls/pull/847#issuecomment-2162042593)

Unless we make this an additional field, we're also going to have issues merging this after the bump, because dataplane-operator needs to be updated to refer to this new name instead of the original `Play`. So, we can probably keep `Play` in this PR along with the new `PlaybookContents`. Once we get this and dataplane-operator merged, we can change it. 

But, then we also need to consider this other piece of work that is going to be painful to rebase:
https://github.com/openstack-k8s-operators/install_yamls/pull/810

So, do we just merge that big PR first. Then come back and address this in a backwards compatible way before trying to make these kind of changes in dataplane-operator and forcing the painful rebase on @fao89

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
I think we need to force merge, CI probably won't pass because:
https://github.com/openstack-k8s-operators/openstack-operator/blob/main/pkg/dataplane/util/ansible_execution.go#L105

**Comment by fao89** [comment]
The alternative to force merge is : 
1- add PlaybookContent, keeping `Play`
2- bump openstack-operator to use `PlaybookContent`
3- drop `Play`

**Comment by fao89** [comment]
https://github.com/openstack-k8s-operators/openstack-operator/pull/854

**Pull request merged**
