### PR TITLE
Report additional mounts in the inventory path and check for conflicts 

### PR DESCRIPTION
**Pull request by jpodivin**

### CODE REVIEW

**Comment by pablintino** [comment]
recheck

**Comment by jpodivin** [comment]
recheck
`"Exception '403\nReason: Forbidden\nHTTP response headers: HTTPHeaderDict({'Audit-Id': 'd06fb8c0-5a5a-4a91-98e7-cc2cbb5db7aa', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '', 'X-Kubernetes-Pf-Prioritylevel-Uid': '', 'Date': 'Sat, 27 Jan 2024 01:05:46 GMT', 'Content-Length': '259'})\nHTTP response body: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"pods is forbidden: User \\\\\"kubeadmin\\\\\" cannot list resource \\\\\"pods\\\\\" in API group \\\\\"\\\\\" in the namespace \\\\\"cert-manager\\\\\"\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"pods\"},\"code\":403}\\n'\nOriginal traceback: \n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/dynamic/client.py\", line 55, in inner\n    resp = func(self, *args, **kwargs)\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/dynamic/client.py\", line 270, in request\n    api_response = self.client.call_api(\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 348, in call_api\n    return self.__call_api(resource_path, method,\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 180, in __call_api\n    response_data = self.request(\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 373, in request\n    return self.rest_client.GET(url,\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/client/rest.py\", line 244, in GET\n    return self.request(\"GET\", url,\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/client/rest.py\", line 238, in request\n    raise ApiException(http_resp=r)\n' raised while trying to get resource using (name=None, namespace=cert-manager, label_selectors=['app = cainjector'], field_selectors=[])"}`

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck `"error: timed out waiting for the condition on openstackdataplanenodesets/openstack-edpm"`

**Comment by jpodivin** [comment]
recheck - `error: timed out waiting for the condition on openstackdataplanenodesets/openstack-edpm-ipam`

**Comment by fao89** [comment]
it is a real error:
https://logserver.rdoproject.org/00/300/ca58e59026d0560d53619917377d9af9029a1448/github-check/podified-multinode-edpm-deployment-crc/e5e42c9/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack-operators/pods/openstack-ansibleee-operator-controller-manager-7c6dfc69668hf97/logs/manager.log

it is timing out because repo-setup couldn't be launched

**Review by fao89 — APPROVED** [review]

**Pull request merged**
