### PR TITLE
Bump and pin dependencies for dev preview

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by gibizer** [comment]
recheck
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "mopenstackdataplane.kb.io": failed to call webhook: Post "https://dataplane-operator-controller-manager-service.openstack-operators.svc:443/mutate-dataplane-openstack-org-v1beta1-openstackdataplane?timeout=10s": endpoints "dataplane-operator-controller-manager-service" not found
```

**Comment by gibizer** [comment]
recheck

**Comment by gibizer** [comment]
recheck
```
Failure downloading https://golang.org/dl/go1.19.10.linux-amd64.tar.gz, Request failed: <urlopen error [Errno 101] Network is unreachable>
```

**Comment by Sandeepyadav93** [comment]
recheck

**Comment by gibizer** [comment]
recheck

```
Error from server (InternalError): error when creating "/home/zuul/ci-framework-data/artifacts/manifests/openstack/nncp/cr/crc-8tnb7-master-0_nncp.yaml": Internal error occurred: failed calling webhook "nodenetworkconfigurationpolicies-mutate.nmstate.io": failed to call webhook: Post "https://nmstate-webhook.openshift-nmstate.svc:443/nodenetworkconfigurationpolicies-mutate?timeout=10s": no endpoints available for service "nmstate-webhook"
```

**Comment by raukadah** [comment]
recheck

**Pull request merged**
