### PR TITLE
Remove description from AnsibleEE CRD

### PR DESCRIPTION
**Pull request by fmount**
This patch rebuilds the `AEE CRD` removing the description to avoid a potential issue when the `AEE` bundle is deployed via `OLM` by the meta operator and the following is seen:

'''
openstack/install-7ws9s"} failed: failed to update installplan bundle lookups: etcdserver: request is too large
'''

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Review by rebtoor — APPROVED** [review]

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Review by fultonj — COMMENTED** [review]
+2

**Review by fultonj — COMMENTED** [review]
+2

**Pull request merged**
