### PR TITLE
Change kuttl tests to run in any namespace

### PR DESCRIPTION
**Pull request by cescgina**
Modify the kuttl tests so that they can run in any namespace, not just
in the openstack one. This requires removing any mention of the
namespace in the asserts and using the $NAMESPACE variable in scripts
instead of the namespace name.

### CODE REVIEW

**Review by slagle — COMMENTED** [review]
+2

**Comment by cescgina** [comment]
https://github.com/openstack-k8s-operators/install_yamls/pull/461 Needs to be merged for CI to pass

**Comment by cescgina** [comment]
@slagle CI is passing now, please take another look when free

**Review by fao89 — APPROVED** [review]

**Pull request merged**
