### PR TITLE
Remove ansibleee-runner-code as we removed this code into edpm-ansibl…

### PR DESCRIPTION
**Pull request by bshewale**
Depends-On: https://review.rdoproject.org/r/c/rdo-jobs/+/46964

### CODE REVIEW

**Review by rebtoor — CHANGES_REQUESTED** [review]
Hey @bshewale, can you also remove the task `build-openstack-ansibleee-runner` from `.github/workflows/build-openstack-ansibleee-operator.yaml`? Thanks in advance!

**Comment by bshewale** [comment]
recheck

**Comment by bshewale** [comment]
recheck

**Review by rebtoor — APPROVED** [review]

**Review by fao89 — APPROVED** [review]

**Pull request merged**
