### PR TITLE
Updating to operator-sdk 1.31

### PR DESCRIPTION
**Pull request by fao89**
Jira: [OSP-26858](https://issues.redhat.com//browse/OSP-26858)

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Comment by dprince** [comment]
In general looks good. I have started work on this as well. Can we track these in https://issues.redhat.com/browse/OSP-26858?filter=-1 so we know who is working on what?

Also, the .ci-operator.yaml file should be updated to use ci-build-root-golang-1.19-sdk-1.31 as the tag now.

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Pull request merged**
