### PR TITLE
Renaming github and quay repos

### PR DESCRIPTION
**Pull request by fao89**
fixes OSP-21337

Signed-off-by: Fabricio Aguiar <fabricio.aguiar@gmail.com>

### CODE REVIEW

**Comment by fao89** [comment]
we need to update prow

**Review by jlarriba — APPROVED** [review]

**Comment by fao89** [comment]
https://github.com/openshift/release/pull/35407

**Comment by jlarriba** [comment]
I think we have an issue with prow having renamed the repository and then make the prow changes. I thought this was the way to go, but it dies not seem to run.

Maybe @raukadah can help us with this.

**Pull request merged**
