### PR TITLE
Multinv doc

### PR DESCRIPTION
**Pull request by jpodivin**
Documentation for the multi-inventory feature.

### CODE REVIEW

**Review by fao89 — APPROVED** [review]
thank you!

**Comment by jpodivin** [comment]
cifmw-crc-podified-edpm-baremetal has hit a retry limit

https://review.rdoproject.org/zuul/build/9edafa1c86d445359bfc95ed49042677

**Comment by fao89** [comment]
/override rdoproject.org/github-check 

it's a docs only PR

**Pull request merged**
